export const SPECIALIZATIONS = [
  'Allergy & Immunology',
  'Anesthesiology',
  'Cardiology',
  'Dermatology',
  'Emergency Medicine',
  'Endocrinology',
  'ENT (Otolaryngology)',
  'Family Medicine',
  'Gastroenterology',
  'General Practice',
  'General Surgery',
  'Geriatrics',
  'Gynecology',
  'Hematology',
  'Infectious Disease',
  'Internal Medicine',
  'Nephrology',
  'Neurology',
  'Neurosurgery',
  'Nutrition',
  'Obstetrics',
  'Oncology',
  'Ophthalmology',
  'Oral & Maxillofacial Surgery',
  'Orthopedics',
  'Pediatrics',
  'Physical Therapy & Rehabilitation',
  'Plastic Surgery',
  'Psychiatry',
  'Pulmonology',
  'Radiology',
  'Rheumatology',
  'Sports Medicine',
  'Urology',
];